#ifndef SCANNING_RATE_CONFIG_H
#define SCANNING_RATE_CONFIG_H

#define SCAN_SYSTEM_DIAMETER 80.0
#define SCAN_SYSTEM_RADIUS (SCAN_SYSTEM_DIAMETER / 2.0)

#define SCAN_OBSTACLE_RADIUS 1.0
#define SCAN_PARTICLE_RADIUS 1.0
#define SCAN_PARTICLE_MASS 1.0
#define SCAN_PARTICLE_SPEED 1.0

#define SCAN_DEFAULT_PARTICLES 100
#define SCAN_DEFAULT_TF 10.0
#define SCAN_DEFAULT_DT 1e-3
#define SCAN_DEFAULT_DT2 0.1
#define SCAN_DEFAULT_K 1e3
#define SCAN_DEFAULT_SEED 0u

#define SCAN_MAX_INIT_ATTEMPTS 1000000

#endif
