import argparse
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.animation as animation
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
import numpy as np


# ==============================
# CONFIG
# ==============================

SYSTEM_RADIUS = 40
OBSTACLE_RADIUS = 1
PARTICLE_RADIUS = 1
VIEW_MARGIN = 1.2
USE_STATE_COLORS = True

# Guias radiales para visualizar capas S (seccion 1.4)
SHOW_RADIAL_GUIDES = False
RADIAL_GUIDES = [2, 5, 10, 20, 30]

# Resaltado especifico para la capa cercana a S = 2
HIGHLIGHT_S2_LAYER = False
TARGET_S = 2.0
DS = 0.2


# ==============================
# PARSER
# ==============================

def parse_args():
    parser = argparse.ArgumentParser(
        description="Create a presentation animation from a dynamic snapshot file."
    )
    parser.add_argument(
        "input_file",
        nargs="?",
        default="output/50_dynamic0.txt",
        help="Dynamic snapshot file generated by the C simulation.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output mp4 path. Defaults to videos/<input basename>_presentation.mp4.",
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=20,
        help="Output video frames per second.",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=50,
        help="Animation interval in milliseconds.",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=600,
        help="Maximum number of snapshots to render. Use 0 to render all.",
    )
    parser.add_argument(
        "--stride",
        type=int,
        default=1,
        help="Use one every STRIDE snapshots before applying max-frames.",
    )
    parser.add_argument(
        "--radial-guides",
        action="store_true",
        help="Show radial guide circles.",
    )
    parser.add_argument(
        "--highlight-s2",
        action="store_true",
        help="Highlight fresh inward particles in the S ~= 2 layer.",
    )
    return parser.parse_args()


def default_output_path(input_file):
    base = os.path.splitext(os.path.basename(input_file))[0]
    return os.path.join("videos", f"{base}_presentation.mp4")


def parse_dynamic_file(filename):
    frames = []

    with open(filename, "r") as f:
        lines = [line.strip() for line in f if line.strip()]

    i = 0

    while i < len(lines):
        n = int(lines[i])
        i += 1

        time_tokens = lines[i].split()
        if time_tokens[0] != "t":
            raise ValueError(f"Invalid snapshot header in {filename}: {lines[i]}")

        t = float(time_tokens[1])
        cfc = int(time_tokens[2]) if len(time_tokens) > 2 else None
        i += 1

        particles = []

        for _ in range(n):
            vals = lines[i].split()

            particles.append({
                "id": int(vals[0]),
                "x": float(vals[1]),
                "y": float(vals[2]),
                "vx": float(vals[3]),
                "vy": float(vals[4]),
                "state": int(vals[5]),
            })
            i += 1

        frames.append((t, particles, cfc))

    return frames


def select_frames(frames, stride, max_frames):
    if stride < 1:
        raise ValueError("stride must be >= 1")

    selected = frames[::stride]

    if max_frames > 0:
        selected = selected[:max_frames]

    if len(selected) == 0:
        raise ValueError("No frames selected")

    return selected


# ==============================
# ANIMATION
# ==============================

def build_animation(frames, args):
    fig, ax = plt.subplots(figsize=(8, 8))

    fig.subplots_adjust(left=0, right=1, bottom=0, top=1)

    ax.set_xlim(-SYSTEM_RADIUS - VIEW_MARGIN, SYSTEM_RADIUS + VIEW_MARGIN)
    ax.set_ylim(-SYSTEM_RADIUS - VIEW_MARGIN, SYSTEM_RADIUS + VIEW_MARGIN)
    ax.set_aspect("equal")
    ax.axis("off")

    outer_circle = Circle(
        (0, 0),
        SYSTEM_RADIUS,
        fill=False,
        color="blue",
        linewidth=4
    )

    inner_circle = Circle(
        (0, 0),
        OBSTACLE_RADIUS,
        fill=True,
        color="red",
        linewidth=2
    )

    ax.add_patch(outer_circle)
    ax.add_patch(inner_circle)

    if args.radial_guides or SHOW_RADIAL_GUIDES:
        for r in RADIAL_GUIDES:
            if OBSTACLE_RADIUS < r < SYSTEM_RADIUS:
                guide_circle = Circle(
                    (0, 0),
                    r,
                    fill=False,
                    color="gray",
                    linewidth=1,
                    linestyle="--",
                    alpha=0.5
                )
                ax.add_patch(guide_circle)

    highlight_s2 = args.highlight_s2 or HIGHLIGHT_S2_LAYER
    if highlight_s2:
        s_bin_start = int(TARGET_S / DS) * DS
        s_bin_end = s_bin_start + DS

        s2_inner = Circle(
            (0, 0),
            s_bin_start,
            fill=False,
            color="orange",
            linewidth=2.5,
            alpha=0.9
        )
        s2_outer = Circle(
            (0, 0),
            s_bin_end,
            fill=False,
            color="orange",
            linewidth=2.5,
            alpha=0.9
        )
        ax.add_patch(s2_inner)
        ax.add_patch(s2_outer)

    particle_patches = []

    for _ in range(len(frames[0][1])):
        patch = Circle((0, 0), PARTICLE_RADIUS)
        ax.add_patch(patch)
        particle_patches.append(patch)

    info_text = ax.text(
        -SYSTEM_RADIUS - 0.5,
        SYSTEM_RADIUS - 1.0,
        "",
        fontsize=12,
        ha="left",
        va="top",
        color="black",
        bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.65, "pad": 4}
    )

    def update(frame_idx):
        t, particles, cfc = frames[frame_idx]

        fresh_count = 0
        used_count = 0
        s2_inward_fresh_count = 0

        s_bin_start = int(TARGET_S / DS) * DS
        s_bin_end = s_bin_start + DS

        for patch, p in zip(particle_patches, particles):
            x = p["x"]
            y = p["y"]
            vx = p["vx"]
            vy = p["vy"]

            patch.center = (x, y)

            if p["state"] == 0:
                fresh_count += 1
                patch.set_color("blue")
            else:
                used_count += 1
                patch.set_color("red" if USE_STATE_COLORS else "blue")

            if highlight_s2:
                r = np.hypot(x, y)
                radial_dot = x * vx + y * vy
                in_s2_layer = s_bin_start <= r < s_bin_end
                fresh_inward = p["state"] == 0 and radial_dot < 0

                if in_s2_layer and fresh_inward:
                    patch.set_color("orange")
                    s2_inward_fresh_count += 1

        info_lines = [
            f"t = {t:.3f}",
        ]
        if highlight_s2:
            info_lines.append(f"S~2 fresh+inward = {s2_inward_fresh_count}")
        info_text.set_text("\n".join(info_lines))

        return particle_patches + [info_text]

    return fig, animation.FuncAnimation(
        fig,
        update,
        frames=len(frames),
        interval=args.interval,
        blit=False
    )


def main():
    args = parse_args()
    output_video = args.output or default_output_path(args.input_file)

    os.makedirs(os.path.dirname(output_video) or ".", exist_ok=True)

    frames = parse_dynamic_file(args.input_file)
    frames = select_frames(frames, args.stride, args.max_frames)

    print(f"Input: {args.input_file}")
    print(f"Frames rendered: {len(frames)}")
    print(f"Output: {output_video}")

    fig, ani = build_animation(frames, args)
    ani.save(output_video, writer="ffmpeg", fps=args.fps)
    plt.close(fig)


if __name__ == "__main__":
    main()
