import argparse
import os

import matplotlib.animation as animation
import matplotlib.pyplot as plt
from matplotlib.patches import Circle


SYSTEM_RADIUS = 40
OBSTACLE_RADIUS = 1
PARTICLE_RADIUS = 1


def parse_args():
    parser = argparse.ArgumentParser(
        description="Animate a scanning-rate dynamic output file."
    )
    parser.add_argument(
        "input_file",
        nargs="?",
        default="output/100_dynamic0.txt",
        help="Dynamic file generated by the C simulation.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="videos/animation.mp4",
        help="Output mp4 file.",
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=20,
        help="Frames per second for the saved animation.",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=50,
        help="Animation interval in milliseconds.",
    )
    return parser.parse_args()


def parse_dynamic_file(filename):
    frames = []

    with open(filename, "r") as handle:
        lines = [line.strip() for line in handle if line.strip()]

    i = 0
    while i < len(lines):
        n = int(lines[i])
        i += 1

        header = lines[i].split()
        if header[0] != "t":
            raise ValueError(f"Invalid snapshot header: {lines[i]}")

        t = float(header[1])
        cfc = int(header[2]) if len(header) > 2 else 0
        i += 1

        particles = []
        for _ in range(n):
            vals = lines[i].split()
            particles.append(
                {
                    "id": int(vals[0]),
                    "x": float(vals[1]),
                    "y": float(vals[2]),
                    "vx": float(vals[3]),
                    "vy": float(vals[4]),
                    "state": int(vals[5]),
                }
            )
            i += 1

        frames.append((t, particles, cfc))

    return frames


def main():
    args = parse_args()
    frames = parse_dynamic_file(args.input_file)

    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_xlim(-SYSTEM_RADIUS - 5, SYSTEM_RADIUS + 5)
    ax.set_ylim(-SYSTEM_RADIUS - 5, SYSTEM_RADIUS + 5)
    ax.set_aspect("equal")
    ax.axis("off")

    outer_circle = Circle(
        (0, 0),
        SYSTEM_RADIUS,
        fill=False,
        color="green",
        linewidth=4
    )
    inner_circle = Circle(
        (0, 0),
        OBSTACLE_RADIUS,
        fill=True,
        color="purple",
        linewidth=2
    )

    ax.add_patch(outer_circle)
    ax.add_patch(inner_circle)

    particle_patches = []
    for _ in range(len(frames[0][1])):
        patch = Circle((0, 0), PARTICLE_RADIUS)
        ax.add_patch(patch)
        particle_patches.append(patch)

    info_text = ax.text(
        -SYSTEM_RADIUS - 4,
        SYSTEM_RADIUS + 2,
        "",
        fontsize=12,
        ha="left",
        va="bottom",
        color="black"
    )

    def update(frame_idx):
        t, particles, cfc = frames[frame_idx]

        for patch, particle in zip(particle_patches, particles):
            patch.center = (particle["x"], particle["y"])
            if particle["state"] == 0:
                patch.set_color("green")
            else:
                patch.set_color("purple")

        info_text.set_text(f"t = {t:.2f}\ncfc = {cfc}")

        return particle_patches

    ani = animation.FuncAnimation(
        fig,
        update,
        frames=len(frames),
        interval=args.interval,
        blit=False
    )

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    ani.save(args.output, writer="ffmpeg", fps=args.fps)
    plt.show()


if __name__ == "__main__":
    main()
